okfn-brasil/serenata-de-amor

- CONTRIBUTING.md
> Recommend Anaconda for setting the project environment

- src/xml2csv.py
This new version of `xml2csv.py` is roughly 4x faster and can be ran in basically any computer (here in my computer it only uses 180Mb of RAM to run).
Basically three new things:
* This versions uses [`xml`](https://docs.python.org/3/library/xml.html)'s [`iterparse`](https://docs.python.org/3.5/library/xml.etree.elementtree.html#xml.etree.ElementTree.iterparse) (and other generators) to parse the XML without loading the full contents into memory (it means I'm not using `BeautifulSoup` to parse the XML)
* It uses the `'a'` mode (*append* mode) instead of the `'w'` mode (*write* mode) to add content to the CSV without open the whole file
* Once memory is not a problem anymore, I replaced file temporary system read & write (slow) by …
> Refactor/optimize with lxml iterparse & StringIO

- README.md
Added crowdfunding at money support session
> Add link to crowdfunding campaign

- develop/2016-08-08-im-translate-dataset.html
- develop/2016-08-08-im-translate-dataset.ipynb
- develop/2016-08-08-im-translate-dataset.py
- src/backup_data.py
- src/fetch_datasets.py
- src/translation_table.py
- src/xml2csv.py
Also adds the [datasets documentation](https://github.com/datasciencebr/serenata-de-amor/pull/25) as one of the datasets to be fetched by default.
> Prevent unnecessary downloads/uploads of datasets and documentation

- README.md
I've changed the display of the words so it is easier to the reader understanding the text idea.
> Changed some words to emphasize project's goals

- setup
The humanize package was missing on Mac, so I added the conda-forge channel to setup to solve this.
> Add conda-forge channel to setup

- CONTRIBUTING.md
Adding a few steps to make it easier for the beginners
> Adding a few steps to make it easier for the beginners

- src/fetch_receipts.py
Follow up to #35 adding support for download images in parallel and executing the download outside the constructor of the class FetchReceipts.
> Multiprocessing to the script that fetches receipt images

- [TL;DR] CEAP.md
TL;DR created for CEAP.
Next steps: translate the document.
> Create TL;DR of Bureau Act describing the CEAP (#69)

- develop/utils.py
Added function to find the sum of value considering unique values of an aggregator
> Added utils.py

- src/fetch_datasets.py
- src/get_family_names.py
Originally created here https://github.com/datasciencebr/serenata-de-amor/pull/93.
> Add new congressperson-relatives dataset to fetch_datasets.py

- config.ini.example
- src/fetch_yelp_info.py
This script is getting data from Yelp API, searching from `trade_name`, `zip_code`, `city` or `lat-long` and saving it in a dataframe.
The Yelp API basicaly needs two params to get info about companies:
A keyword, here we're using `trade_name`.
Specifies the combination of "address, neighborhood, city, state or zip, optional country".
Required if location is not provided. Latitude of the location you want to search near by.
_**I tested with one more param:**_
Optional. Search radius in meters. If the value is too large, a AREA_TOO_LARGE error may be returned. The max value is 40000 meters (25 miles).
I tested with 7 combination of those params and [lat-long](https://github.com/datasciencebr/serenata-de-amor/blob/75a0fbc791a1a596cd68520a706f9ee427695f5f/src/fetch_yelp_info.py#L98) fetched …
> Script to fetch Yelp data about companies in meal reimbursements

- config.ini.example
- src/fetch_foursquare_info.py
It tries to find a match in foursquare API using our companies dataset. It uses trade_name, zip_code, latitude and longitude values.
> Script to fetch foursquare data about companies in meal reimbursements

- develop/2016-12-07-irio-election-expenses.html
- develop/2016-12-07-irio-election-expenses.ipynb
- develop/2016-12-07-irio-election-expenses.py
Recently we found a congressperson who made an allegedly postal service expense in a company created for his own benefit, for his next candidacy in elections.
We believe there are more cases like this one.
Result: There are. Currently, 47 suspects. Not all of them were in congressperson's own benefit, but for other candidates. Still, could be reported to the Chamber of Deputies.
> Search for reimbursements made for election companies

- CEAP.md
Super minor, but I think this reads better 😄
> Fix indentation on CEAP doc

- CONTRIBUTING.md
- docker/Dockerfile
- docker/jupyter_notebook_config.py
Hey guys! Great work on this project, 🍻 / 🍷 / ☕️ to everyone involved 😄 
While I'm still trying to find out how can I help on the data side of things, I noticed some improvements we can make to the Docker dev environment, namely reducing the amount of layers and size of the resulting image:
_The second image is the one I built with the code that is on master_
... and setting up the automagic `.html` / `.py` creation when saving notebooks.
> Docker tweaks

- CONTRIBUTING.md
I made a few changes to the CONTRIBUTING.md file, in order to fix small mistakes and help with clarity. I tried to keep changes to a minimum, since all I know about the code came from that same file (hardly in-depth). I apologize if any of the changes are mistaken; otherwise, I would gladly help with a few more rewrites.
> Fixed a few mistakes on CONTRIBUTING.md

- CONTRIBUTING.md
> Fix toolbox docs URL and use "the toolbox" in the text

- develop/2017-02-20-anaschwendler-expenses-in-closed-companies.html
- develop/2017-02-20-anaschwendler-expenses-in-closed-companies.ipynb
- develop/2017-02-20-anaschwendler-expenses-in-closed-companies.py
I'll thank @jtemporal later, but by now its only missing the date comparision. ❤️
> Expenses in closed companies

- src/fetch_sex_places.py
*Fix docstring inconsistences;
*Passes empty str ('') at `company_name`, `company_trade_name` instead of `None` value;
> Refactor sex related places

- conda_requirements.txt
> Fix beautifulsoup4 version on requirements

- develop/2017-05-02-anaschwendler-translate-senate-dataset.html
- develop/2017-05-02-anaschwendler-translate-senate-dataset.ipynb
- develop/2017-05-02-anaschwendler-translate-senate-dataset.py
As we say in [this article](https://medium.com/data-science-brigade/expandindo-a-serenata-de-amor-para-outras-esferas-48bed204d36d), we are expanding our project to other datasets, the first one will be the Senate Quota dataset.
The datasets may be still added here later.
We will start by adding them to the `serenata-toolbox`, then we can use it here.
TODO:
> Senate dataset first analysis notebook.

- develop/2017-05-11-anaschwendler-checking-federal-senate-reimbursements.html
- develop/2017-05-11-anaschwendler-checking-federal-senate-reimbursements.ipynb
- develop/2017-05-11-anaschwendler-checking-federal-senate-reimbursements.py
This PR is a study for the [`serenata-toolbox` Federal Senate dataset](https://github.com/datasciencebr/serenata-toolbox/pull/53).
We already made a script that `fetch()` and `translate()` the nine datasets, divided by year from 2008 to 2017, but we need to `clean()` that dataset, concat and group the information, a study about the dataset to see what we need to do in the `serenata-toolbox` script.
So we are taking a few steps back to do everything right :)
Looking for an evaluation from @jtemporal and @cuducos !
It's coming!
🎉
> Start of a long study about the Federal Senate dataset

- src/fetch_cnpj_info.py
I did some improvements in the fetch_cnpj_info to handle requests failed. I noticed that during the for loop some of the futures with errors were not getting reinserted in the loop maybe because of [this](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.as_completed):
> Any futures given by fs that are duplicated will be returned once.
So I created a outer loop which runs until there is no more cnpjs left to fetch.
> handling for failed cnpj info requests in fetch_cnpj_info.py

- develop/2017-05-21-luizcavalcanti-chamber-ceap-api-version-comparison.html
- develop/2017-05-21-luizcavalcanti-chamber-ceap-api-version-comparison.ipynb
- develop/2017-05-21-luizcavalcanti-chamber-ceap-api-version-comparison.py
Since the project core team uploaded the dataset
snapshots for both version 1.0 and 2.0 of Chamber's
CEAP to the S3 instance, we're updating the notebook
to download them from there.
Signed-off-by: Luiz Carlos Cavalcanti <cavalcanti.luiz@gmail.com>
> Modified notebook to download data from S3

- src/grequests_transparency_portal_cities.py
Signed-off-by: Luiz Carlos Cavalcanti <cavalcanti.luiz@gmail.com>
> Initial refactor on cities transparency fetch

- src/grequests_transparency_portal_cities.py
Signed-off-by: Luiz Carlos Cavalcanti <cavalcanti.luiz@gmail.com>
> Correct small nuisances in transparency portal retrieval

- CONTRIBUTING.md
- conda_requirements.txt
- docker/Dockerfile
- requirements.txt
Not sure if this is going to break things for people running the env outside of Docker but this is what I've done to get up and running again after reformating my laptop.
Tks to @cabral for the tip on using the `bioconda` channel.
BTW, things look a lot nicer on this new jupyter release 😍 
/cc @cuducos
> Update docker image and fix issues with conda packages installation

- CONTRIBUTING.md
Just a small typo fix in the documentation
> Fix typo in word dataset

- src/fetch_tse_data.py
> Fixing fetch tse data scrapper

- CONTRIBUTING.md
`/research/report` -pointing to '/research/deliver' instead
> Fix doc referring to a dir that doesn't exist

- README.md
Adding a donate button to the README file, referencing https://github.com/datasciencebr/serenata-de-amor/issues/283.
> Add donate button

- CONTRIBUTING.md
This reverts commit 718a74e031ea0a4b020bf42801e1d23353e6bc34, reversing changes made to 3cc108a6a1a2395bdf65bf34d23dfd0a05ddabcd and cleanup unnecessary command to run `serenata-de-amor` in Docker.
---
**UPDATE**: As described in #292 and #274
> Revert "Merge pull request #287 from arioston/master" and cleanup

- research/develop/2017-11-25-mathcunha-ceap-expenses-descriptive-analysis.py
The info to answer the questions can be found at 2017-07-04-reimbursements.xz. 
But, to answer Question 2, I had to collect quota information available at http://www2.camara.leg.br/comunicacao/assessoria-de-imprensa/cota-parlamentar.
To complete the quota information, I used the same approach presented at 2017-05-01-luipillmann-intro-to-reimbursements.ipynb
> Issue #295 - New descriptive analysis

- .pyup.yml
- research/requirements.txt
Added pyup.io config file.
The necessary changes were made to the config file. The pyup.io test will run weekly, and added label enhancement for the updates by pyuo.io. pyup.io will ignore serenata-toolbox as well.
Pyup test needs to be run and tested.
@cuducos 
**TODO**
> added config file for pyup

- README.md
Update the domain in the `README.md` link.
> Change domain: serenatadeamor.org -> serenata.ai

- contrib/.env.sample
- docker-compose.yml
- research/requirements.txt
- research/src/fetch_foursquare_info.py
- research/src/fetch_inbox.py
- research/src/fetch_sex_places.py
- research/src/fetch_yelp_info.py
- research/src/geocode_addresses.py
The missing references are needed by serenata-toolbox. Once we change the toolbox, we can update this repository again.
> Use decouple package to read vars from env vars, not config.ini file

- research/CONTRIBUTING.md
- research/Dockerfile
- research/setup
- rosie/.gitignore
- rosie/Dockerfile
- rosie/README.md
- rosie/config.ini.example
- rosie/setup
We are already changed `serenata-toolbox` to not use `config.ini` any more, and now we are changing this repo to reflect the changes.
Just checked where there was still `config.ini` selected and changed it. Now we are using `python-decouple` to set variables.
Just check if everything is working properly, following the `README.md` from all projects
@cuducos @Irio
> Update serenata de amor config.ini

- contrib/.env.sample
- docker-compose.yml
- jarbas/settings.py
Adds missing .env clause in `docker-compose.yml` file.
> Use WhiteNoise only when not in debug mode

- contrib/.env.sample
- jarbas/chamber_of_deputies/tests/test_reimbursement_view.py
- jarbas/settings.py
While working on #360 I found minor room for improvements, the commits are self-explanatory (feel free to squash them on merge).
**What was done ~~to achieve this purpose~~?**
* I've found some vars missing from the sample `.env` so I added them (7beafaa)
* I found the first-block of the sample `.env` too big to and re-sorted it (8fe86f2)
* While exploring some performance issues for (#360) I missed the Django Debug Tool bar, so I configured it properly for Docker environments using a dynamic `INTERNAL_IPS` alternative (96e7574)
* The linter has pointed out a tab invading our `settings.py` and I squashed it using 4 spaces instead (6db1ab8)
I would recommend three simple things:
1. If there's no typo or any …
> WIP Minor fixes and enhancements on envvars & settings

- jarbas/chamber_of_deputies/tests/test_reimbursement_view.py
This PR is to include tests on some filters that did not have tests.
- month
- applicant_id
- year
Three new tests were included in the changed file. Following the same model of the existing tests for the other filters.
I only did the tests :)
This is my first PR in the repository. From now on I intend to begin to understand the project and get to know the people. Nowadays, I do not know who would be better indicated.
> More Tests on Reimbursement View Api

- CONTRIBUTING.md
- rosie/README.md
Instructions to run Rosie weren't working – it looks like we had an `ENTRYPOINT` that have been removed at some point, so the docs were outdated.
Updated the docs adding the missing `python rosie.py` to Docker instructions when needed.
Copy and paste Docker commands from `CONTRIBUTING.md` and `rosie/README.md` and make sure they work ; )
@anaschwendler @jtemporal @Irio @cabral
> Update Rosie docs

- .travis.yml
- README.md
- jarbas/README.md
- rosie/README.md
We used to have CI and their badges for Jarbas and Rosie. This PR brings them to the main repo ; )
* Registered this repo in Code Climate for code quality analysis and test coverage
* Change `.travis.tml` to use Code Climate test coverage updater (instead of coveralls)
* Added badges in `REAMDE.md`
* Removed badges from `jarbas/README.md` and `rosie/README.md`
* Check webhooks here in this PR to make sure you have CodeClimate added to the list
* Check badges in the home of this repo at GitHub
@anaschwendler @Irio @cabral @jtemporal
> Add CI & badges

- CONTRIBUTING.md
Following @rogeriochaves's feedback on https://github.com/okfn-brasil/serenata-de-amor/pull/365#issuecomment-385259348
> Fix Jarbas docs on CONTRIBUTING.md

- package-lock.json
Fiz NPM `hoek` package vulnerability by using newer versions.
> Fix hoek vulnerability

- README.md
Fix toolbox link on readme.md.
Changed the link to the correct Github link.
Use the github markdown viewer and access the link to the toolbox on readme.
I don't know.
> Fix Toolbox Link

- rosie/setup
for this (https://github.com/okfn-brasil/serenata-de-amor/issues/400)
new version pip.main is changed to pip._internal.main  
in the new version pip 10
> fix pip.main  for new version

- Dockerfile
- goss.yaml
- jarbas/core/tests/test_healthcheck_url.py
- jarbas/core/views.py
- jarbas/urls.py
As described by @willianpaixao in #429, we are not making a good use of Goss, so we could replace it by something simpler and make the Docker image smaller and simpler.
As explained in #429:
* Removed Goss
* Add a `/healthcheck` endpoint
* Replaced the `HEALTHCHECK` in the `Dockerfile`
Not sure. Any ideas?
@willianpaixao @jtemporal
> Remove Goss (use simpler health check)

- jarbas/layers/elm/Reimbursement/View.elm
Fix #464
Fixed link on Jarbas Elm view
I could run Jarbas locally, so I don't tested the link with new format. I think that running it and testing some links would be enough.
I think that @cuducos can review it.
> Fix link to the deputies profile on Jarbas

- CONTRIBUTING.md
Just fix a filename that seems incorrectin the contribution documentation.
The filename was changed.
Not applicable. It's just a Markdown :) But copy&paste&execute the modified command seems to work
**TODO**
> Fix reimbursements sample filename

- rosie/rosie/core/__init__.py
It had some misspelling and minor grammar issues on Rosie's core class. 
Improve readability of Rosie's core class
Rewriting of some sentences of the docstring.
Just read it :D!
@cuducos and @sergiomario 
**TODO**
> Fix Rosie's core class doc

- jarbas/README.md
Rosie hypterlink from https://github.com/okfn-brasil/rosie to https://github.com/okfn-brasil/serenata-de-amor/tree/master/rosie
> Adjust jarbas README

- jarbas/dashboard/admin/list_filters.py
Add electronic receipt filter in Jarbas UI. This should solve issue #519
Added the new filter in Jarbas UI.
Go to the document type filter list in Jarbas and see the new eletronic receipt item. Click on it and check if it showing just eletronic receipts reimbursement.
Anyone
> adding eletronic receipt filter in jarbas UI
