okfn-brasil/serenata-de-amor

.gitignore
src/xml2csv.py

As I said, it's way slower than the previous method, but I could convert `AnosAnteriores.xml` (2.6G) into `AnosAnteriores.csv` (291M) with my MacBook (8Gb RAM, Core M) — it took more than 4 hours though.

Refactor xml2csv.py to run with less RAM

---

conda_requirements.txt
config.ini.example
src/backup_data.py
src/clean_cnpj_info_dataset.py
src/fetch_cnpj_info.py
src/fetch_datasets.py
src/geocode_addresses.py

Comes to solve our need (#14) of addresses and coordinates of all companies listed in the expenses. The initial version is the result a collaboration between me, @filipelinhares and @andrepinho.
Here's a short summary of what the current dataset has (not sure if this notebook fits well in the repository, probably not): https://gist.github.com/Irio/002a1d3842466aacd0027c6f382a2d9b
Once this pull request gets approved, I will uploaded it to Amazon S3.
Current version of the dataset contains a list of 59,985 companies; when counting just the Brazilian ones, 3,453 are missing given timeouts returned by the API used.
**Missing**

New dataset with companies information

---

CONTRIBUTING.md
README-en.md
README.md
src/translation_table.py

Documentation: datasets, source files, clean up & mention to Jarbas

---

setup

If you're following recommendations in the [CONTRIBUTING.md](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#environment), will correctly point to `~/anaconda3/envs/serenata_de_amor/bin/python3`. Otherwise, will at least use Python 3 if available in the system.
Fixes #59.

Change setup script to Python 3 shebang

---

.gitignore
CONTRIBUTING.md
README-en.md
README.md
conda_requirements.txt
config.ini.example
develop/2016-08-08-im-translate-dataset.html
develop/2016-08-08-im-translate-dataset.ipynb
develop/2016-08-08-im-translate-dataset.py
develop/2016-08-13-im-descriptive-analysis.html
develop/2016-08-13-im-descriptive-analysis.ipynb
develop/2016-08-13-im-descriptive-analysis.py
setup
src/backup_data.py
src/clean_cnpj_info_dataset.py
src/fetch_cnpj_info.py
src/fetch_datasets.py
src/fetch_receipts.py
src/geocode_addresses.py
src/translation_table.py
src/xml2csv.py

This is a program to download receipts to a local directory (fix #33).
```console
$ python src/fetch_receipts.py
This script downloads the receipt images from the Lower House server.
Be aware that downloading everything might use more than 1 TB of disk
space.  Because of that you have to specify one `target` directory (where
to save the files) and optionally you can specify with `--limit` the number
of images to be downloaded.
If the `target` directory exists and already has some saved receipts,
these receipts will not be downloaded again (and they will not count when
using `--limit` either).
In other words, if you already have 42 receipts in your target folder,
running the command with a limit of 8 will end up in a directory with 50
files: the 42 you already had and 8 freshly downloaded …
```

Script to fetch receipt images

---

conda_requirements.txt

The ‘xz’ compression, that is being used in the datasets, was introduced in pandas version 0.18.1.

Add pandas>=0.18.1 to requirements

---

CONTRIBUTING.md
README.md
docker-compose.yml
docker/Dockerfile

This PR adds a Dockerfile to the project and update the documentation explaining how to use it. 
The docker-compose was already created in version 2 syntax (as suggested by @gwmoura)
And I also fixed some typos in documentation.
p.s.: There is a problem when reading csv in the current notebooks. But I think it is an issue for another pull request. I'm working on that.

Add dockerfile

---

CONTRIBUTING.md

The current hook proposed in the best practices section of
CONTRIBUTING.md to auto-convert notebooks to .py and .html formats
has a slightly minor problem: it uses a deprecated command, as stated
in the stdout every time the hook gets called:
```
[TerminalIPythonApp] WARNING | Subcommand `ipython nbconvert` is
deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter
nbconvert` in the future
```
This PR fix the recommendation, orientating users to use the new
approach (jupyter nbconvert) instead of the old one. There should not
be any side effects.

Upgrade auto-conversion hook to remove deprecation

---

CEAP.md
CONTRIBUTING.md

I added a step to the Source files/Quota for Exercising Parliamentary Activity (CEAP) section on the CONTRIBUTING.md file to explain how to generate the YYYY-MM-DD-reimbursements.xz file used in most of the /develop samples.

Include step in the documentation to generate the reinbursements file

---

CONTRIBUTING.md
docker/Dockerfile
docker/jupyter_notebook_config.py

Follow up of a discussion over Telegram, this PR:
- Locks the docker image to a known to work tag for reproducibility
- Updates contributing info with the size of the image in use
- Disables authentication altogether (the OP on Telegram mentioned he had issues with the token that was generated for him). I don't think this is an issue since this is not meant to be used in production AFAIK.
/cc @cuducos

Docker dev environment tweaks

---

CONTRIBUTING.md

Basically offer an alternative to nix OS `./` for execution and `source` for… well… sourcing.

Make install instructions friendly for Windows users

---

config.ini.example
src/backup_data.py

This PR:
* Fixes `config.ini.example` (`s3-sa-east-1` is not a _region_, it's a region prepend by a service, so or new default is `sa-east-1` only)
* Use new `Datasets` module from the toolbox in the backup script

Use the new datasets module

---

develop/2016-12-30-fgrehm-ocr-receipts-with-google-cloud-vision.html
develop/2016-12-30-fgrehm-ocr-receipts-with-google-cloud-vision.ipynb
develop/2016-12-30-fgrehm-ocr-receipts-with-google-cloud-vision.py

As I mentioned over Telegram, I did a quick spike on using [Google's Cloud Vision API](https://cloud.google.com/vision/) to OCR a few receipts and this notebook showcases the results I found. I used different receipts this time and the results look a bit more promising.
Unfortunately it would take me a while to get this right in Python so I just kept it simple and did with just bash. All the files related to it (pdf, payloads and responses) can be grabbed from the Zip below in case someone wants to play with it as well.
[reimbursements-ocr.zip](https://github.com/datasciencebr/serenata-de-amor/files/678854/reimbursements-ocr.zip)

Spike on OCR receipts with Google Cloud Vision API

---

.gitattributes

It will make the repository be better classified in the expected languages
on GitHub.
I expect to change the classification for something better describes the contents of the repo, making it a project made of Jupyter Notebooks.
Docs:
https://github.com/github/linguist/tree/b94e018c3af1ca5b3858f2249253d076b26df6a0#generated-code

Ignore HTML and PY files in Linguist

---

CONTRIBUTING.md
docker-compose.yml
research/Dockerfile
research/requirements.txt
setup

This PR fixes three bugs in the Docker install files and instructions:
* `config.ini` wasn't available inside `research` Docker conatiner causing `seretana_toolbox` to fail
* Docker instructions depended on a deprecated script (`src/fetch_datasets.py`)
* In addition it run `setup` script by default during the Docker container build (fixing the previous bullet point and somehow _testing_ the first bullet point)
**Disclaimer:** as titled and labeled this is a _work in progress_. I coded that in a bus and pushed it using 3G — but I haven't tested it yet. Gonna test (and probably fix whatever I got wrong in the infamous _brain code compiler_ as soon as I reach civilization and wifi).

Fix Docker install

---

setup

The latest version of `setup` is not compatible with some Windows users because of hardcoded `/` in directory paths. This PR fixes that ; )

Fix paths for Windows users

---

research/Dockerfile

Bug:
Given serenata-de-amor cloned from github, built by docker-compose and up by docker-compose
When editing a Jupyter notebook from directory work/develop
Then causes "PermissionError: [Errno 13] Permission denied: '/home/jovyan/.jupyter/migrated'"
Bug analysis:
Directory /home/jovyan/.jupyter with owner root and jupyter process with owner jovyan
Root cause:
COPY command of Docker creates files and directories with a UID and GID of 0, according to [documentation](https://docs.docker.com/engine/reference/builder/#copy) and pointed on this [thread](https://stackoverflow.com/questions/44766665/how-do-i-docker-copy-as-non-root).
Solution:
Setting owner jovyan for directory /home/jovyan/.jupyter

#276 - Fixed error on editing Jupyter notebook

---

setup

This PR depends on https://github.com/datasciencebr/serenata-toolbox/pull/133
If the user wants to download all the datasets from serenata-toolbox, he can pass an option to the command `./setup`. Usage: `./setup --all`.

Add option to download all datasets from serenata-toolbox

---

CONTRIBUTING.md

Hi,
I had made a change on CONTRIBUTING.md, because --rm don't expose the ports.

Jupyter Notebook not available (docker) #274

---

research/requirements.txt

All Amazon S3 handling is done by `serenata-toolbox` so we don't need `tinys3` anymore.
Just a tiny cleanup on `requirements.txt`: I removed `tinys3` line.
Hum… some options:
1. From a fresh install try every script and check they don't break
2. From an existing install `pip uninstall tinys3`, try every script and check they don't break
3. Just check every script to make sure `tinys3` is never called or imported (GitHub search, `grep`, [`ag`](https://github.com/ggreer/the_silver_searcher) or [`ack`](https://beyondgrep.com/) might be your friend)
@anaschwendler

Remove tinys3

---

README.md

Totally _nail care_ based probably on my OCD, but I think visually speaking it's a nice thing to use mono-spaced font for the BTC address: it clearly separates the arguably random string from the rest of the text and avoid confusing `O` with `0` in an important string ; )
Added the proper markers to show the BTC address with mono-spaced font in MarkDown renders.
Just check [the visual version of the `README.md` in this PR](https://github.com/okfn-brasil/serenata-de-amor/blob/3ead79ed992d8264a50f73a11f36e23d6823d2fe/README.md).
**Who are the best people to help reviews it?**
@anaschwendler

💅 Re-add monospaced font for BTC address

---

requirements.txt

Other PRs are failing because the version we're currently using is
marked as unsafe by pyup.io. This PR brings New Relic package to it's
latest version.

Update New Relic Python package

---

jarbas/dashboard/admin.py

**Making safe to show object proprieties**
Jarbas was showing strings with html tags that are not rendered
Run `docker-compose up django` and access `localhost:8000`. The first info should be a readable name
Was 
Now

django 2 update: making string safe to show

---

README.md

This fixes incorrect link on `README.md`.
It also creates a newline at the end of the file, I didn't add it manually and edited the file using te GitHub interface to make sure it was not a configuration of my text editor doing that.

Correct Tech Crash Course link on README.md

---

jarbas/dashboard/admin.py

I noticed the home of the reimbursements in the dashboard required **105** queries in order to load the reimbursement list. That was ludicrous.
I used the `list_select_related` and reduced the queries from 105 to only 5. This means more speed and less overload in our database.
Open the dashboard and check if all expected info is still there ; )
@anaschwendler @Irio @jtemporal @cabral

Optimize query in the dashboard

---

.travis.yml
contrib/.env.sample
jarbas/chamber_of_deputies/tests/test_reimbursement_view.py
jarbas/settings.py

Replaces #361 that was accidently merged.
---
While working on #360 I found minor room for improvements, the commits are self-explanatory (feel free to squash them on merge).
**What was done ~~to achieve this purpose~~?**
* I've found some vars missing from the sample `.env` so I added them (1e6688f)
* I found the first-block of the sample `.env` too big to and re-sorted it (ca61fec)
* While exploring some performance issues for (#360) I missed the Django Debug Tool bar, so I configured it properly for Docker environments using a dynamic `INTERNAL_IPS` alternative (9f4d738)
* The linter has pointed out a tab invading our `settings.py` and I squashed it using 4 spaces instead (5b518e5)
* I've noted that a certain test was (unecessarily) …

Minor fixes and enhancements on envvars & settings

---

jarbas/README.md
jarbas/chamber_of_deputies/querysets.py
jarbas/chamber_of_deputies/tests/test_reimbursement_view.py
jarbas/chamber_of_deputies/views.py

Making the filter available by name of the policy makes it easy for customers to use the API and create user-friendly interfaces. For example, a chat bot where the user can follow certain person and for that he needs to do a search by name.
I placed one more option among the query string filters `congressperson_name__contains`. It is important to note that this field is already indexed in the database.
Also included was the test and updated documentation.
In commit there is an altered test file, looking at the differences it is easy to see the test, it follows the others. Run the project tests that it will run together.
I do not know …

New filter field on reimbursement view Api

---

jarbas/chamber_of_deputies/management/commands/searchvector.py
jarbas/chamber_of_deputies/tests/test_reimbursement_view.py
jarbas/chamber_of_deputies/tests/test_searchvector_command.py
requirements.txt

The `searchvector` Jarbas command took too long and offered now progress feedback to the user. Also it was quite heavy on the database.
* Update in batches/slices to be more friendly to the database server
* Use `tqdm` to show the progress based on these batches, to be more friendly with the user
Just [run the `searchvector` command](https://github.com/okfn-brasil/serenata-de-amor/tree/master/jarbas#creating-search-vector). As we need a new dependency (`tqdm`) pip-installed you might need to change your `docker-compose.yml` locally:
```diff
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -9,7 +9,9 @@ services:
- ./rosie:/code
django:
-    image: serenata/django …
```

Add progress bar to search vector command

---

rosie/rosie/chamber_of_deputies/adapter.py
rosie/rosie/chamber_of_deputies/tests/test_adapter.py

**What is the purpose of this Pull Request?** 
Big picture: to improve the stage of coercing dates.
- Specify a format when converting issue_field do datetime, to make clear what format we expect as input.
- Fix a bug on coercing situation_date and tuning performance of this stage.
The bug is after coercing situation_date without specifying the format, many dates were with day/month instead month/day, (ex: 05/11/2017 were coercing to 2017-05-11).
The initial focus of my work was tuning the performance of the coerce situation_date stage:
- a DataFrame with 1860489 items was taking 140 seconds to coerce situation_date. After specifying the format, it was taking 10 seconds
It was specified a format when coercing these date fields
**How to test if it …

Bugfix and enhancements on coercing dates stage

---

docker-compose.yml
jarbas/dashboard/admin.py
jarbas/dashboard/admin/__init__.py
jarbas/dashboard/admin/list_filters.py
jarbas/dashboard/admin/paginators.py
jarbas/dashboard/admin/subquotas.py
jarbas/dashboard/admin/widgets.py
jarbas/dashboard/tests/test_dashboard_admin.py

Jarbas Dashboard is still extremely slow and now I attempt to use cache in order to make it faster.
* Cache Django Admin `COUNT` queries
* Cache `DISTINCT` queries used to build Django Admin filters such as state and year
Spin up the services and browser [the dashbaord](http://0.0.0.0:8000/dashboard/chamber_of_deputies/reimbursement/) to check I haven't broken anything. If you have the Django Toolbar enabled you can check cache is working playing around with `CACHE_BACKEND` envvar.
**TODO**
We need to make sure the cache is working on production servers. I noticed it was removed from the `docker-compose.yml`, so I'm not sure if it's in our private …

Optimize Jarbas Dashboard using cache

---

jarbas/README.md
jarbas/chamber_of_deputies/querysets.py
jarbas/chamber_of_deputies/tests/test_reimbursement_view.py
jarbas/chamber_of_deputies/views.py

This Pull Request add a state filter to the reimbursement view endpoint
`state` was added to the list of params of the ReimbursementListView using the lookup [`iexact` (Case-insensitive exact match.)](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#iexact).
`docker-compose run --rm django python manage.py test jarbas.chamber_of_deputies.tests.test_reimbursement_view.TestListApi.test_content_with_state_filter`
Anyone who knows the api =)
It closes the issue #402

Filter reimbursements by state

---

jarbas/chamber_of_deputies/serializers.py
jarbas/chamber_of_deputies/tests/test_reimbursement_view.py
jarbas/chamber_of_deputies/tests/test_serializers.py
jarbas/chamber_of_deputies/views.py
jarbas/dashboard/admin/__init__.py

Resolves https://github.com/okfn-brasil/serenata-de-amor/issues/448. Currently is not possible to retrieve imbursements from a masked CNPJ/CPF.
Now both AdminSite and API has a method to clean masked CNPJ/CPF.
Run Jarbas and test the search by using a masked and a not masked CNPJ or CPF. Like: 07575651000159 and 07.575.651/0001-59. Both must return the same results.
@cuducos maybe? :) I've used his snipet code.
**TODO**
Searching by CNPJ/CPF is only possible if a user types the whole document (14 or 18 characters). Maybe would be nice adding support to partial CNPJ/CPF.

Support masked CNPJ/CPF on the search

---

contrib/update/README.md
contrib/update/ansible.cfg
contrib/update/cleanup.py
contrib/update/cleanup.yml
contrib/update/update.yml
requirements.txt

Jarbas `update` command was taking too long and causing Ansible to crash with a SSH connection error. Also the `cleanup.yml` was failing (from times to times) to remove the existing droplet.
* Set Ansible to better deal with processes that take too long, using `async` strategy
* Replace the cleanup playbook by a Python script
Having access to DigitalOcean droplets, just run the Ansible playbook as documented in `contrib/update`.

Fix update: long processes where failing

---

jarbas/chamber_of_deputies/models.py
jarbas/dashboard/admin/__init__.py
jarbas/dashboard/static/dashboard.css
jarbas/dashboard/templates/dashboard/reimbursement_summary_change_list.html
jarbas/dashboard/templatetags/dashboard.py

Based on @hakib's post (many thanks!) [How to turn Django Admin into a lightweight dashboard](https://hakibenita.com/how-to-turn-django-admin-into-a-lightweight-dashboard) I suggested an implementation for Jarbas. This might be useful for non-tech people interested in an simple overview of CEAP (cc @tatianasb and @vilapedro).
Basically followed the steps in @hakib's post.
Run Jarbas, reach `/dashboard/chamber_of_deputies/reimbursementsummary/` and expect I expect you can browse in an interface like this one:
Just thinking out loud depending on each one's interest and availability: @jtemporal @giovanisleite @cabral @turicas @irio …

Add summary table and charts to the Dashboard

---

jarbas/layers/elm/Reimbursement/Decoder.elm
jarbas/layers/elm/Reimbursement/Model.elm
jarbas/layers/elm/Reimbursement/View.elm

This is probably an error in the original datasets, as described in #457. This commit can be reverted later depending on the response from the Chamber of Deputies: https://github.com/labhackercd/dados-abertos/issues/215

Make term field optional in Elm

---

jarbas/chamber_of_deputies/twitter.py

Due to Twitter's suspension of Rosie API keys, we are not mentioning the chamber of deputies in the tweets (at least for now). More on this case (in Brazilian Portuguese, English version soon): https://medium.com/serenata/a-suspens%C3%A3o-da-rosie-no-twitter-mostra-como-as-regras-para-bots-ainda-precisam-ser-lapidadas-94a0ab8b0003
The `Tweet` class, responsible for the logic of picking up a suspicions, writing and posting the tweet, now takes a boolean argument `mention`. And we encourage Rosie followers to mention the congressperson if they wish ; )
Import the `Tweet` class and check the message is what you expect. For example:
```python
>>> from …
```

Remove mentions from tweets

---

jarbas/chamber_of_deputies/twitter.py

@tatianasb suggested Rosie to tweet only suspicions within the last 2 years, not from the current (or last) legislature available.
This commit implements two strategies to make Rosie tweet newer
suspicions:
* It filters reimbursements considering the last two years
* It organizes the `QuerySet` by descending issue date and returns the top
quartile

Make Rosie tweet newer suspicions

---

jarbas/dashboard/static/dashboard.js

Only a small refactoring that helps in the readability of the code. But if you look for performance `indexOf` is more recommended.
> ## Motivation
>When using ECMAScript arrays, it is commonly desired to determine if the array includes an element. The prevailing pattern for this is
>
>```js
>if (arr.indexOf(el) !== -1) {
>    ...
>}
>```
>
>with various other possibilities, e.g. `arr.indexOf(el) >= 0`, or even `~arr.indexOf(el)`.
>
>These patterns exhibit two problems:
>
>- They fail to "say what you mean": instead of asking about whether the array includes an element, you >ask what the index of the first occurrence of that element in the array is, and then compare it or bit->twiddle it, to determine the answer to your actual question.
>- They …

refactor: Introduce Includes

---

CONTRIBUTING.md
README.md

Since 99de387e this repo doesn't host the exploratory notebooks any more, however `README.md` and `CONTRIBUTING.md` were still mentioning this directory as @ghmc91 alerted us in the Telegram group.
I updated  `README.md` and `CONTRIBUTING.md` removing references to to this part of the project.
Read and check whether new contents still make sense ; )
@sergiomario

Remove research directory from docs

---

CONTRIBUTING.md

Hi,
Here we simply add a step in `CONTRIBUTING.md` to run the project migrations before spinning up the containers.

Add step to run django migrations in setup

---

jarbas/layers/elm/Reimbursement/Company/View.elm

Here we remove the street view functionality from Jarbas' reimbursements view. This is is the result of the following issue discussion https://github.com/okfn-brasil/serenata-de-amor/issues/441
All the elm code related to rendering the four street view tiles are removed.
Access a reimbursement that previously showed the street view tiles and check that it doesn't show anymore.
Here's how it looks like:

Remove streetView functionality

---

jarbas/chamber_of_deputies/twitter.py

This proposal was made to implement issue #468 
According to the rules of parliamentary quota of the Chamber of Deputies, Members have up to 90 days to present the supporting documentation of expenditure.
"No caso de reembolso, o deputado tem até 90 dias para apresentar a documentação comprobatória do gasto, depois da data de prestação do serviço ou de fornecimento do produto. "
I put a date filter to disregard suspicions from the last 90 days.
@cuducos and @cacarrara

Rosie should post tweets where suspicions that have at least 91 open days

---

jarbas/chamber_of_deputies/models.py
jarbas/chamber_of_deputies/tests/test_receipt_class.py
jarbas/layers/elm/Internationalization.elm
jarbas/layers/elm/Internationalization/DocumentType.elm
jarbas/layers/elm/Reimbursement/Company/View.elm

Fix the receipt URL of those reimbursements that the receipts are electronic
The class `Receipt` was modified to build the `receipt_url` differently when the `document_type` indicates that it is of the electronic type (https://github.com/CamaraDosDeputados/dados-abertos/issues/268).
You have to have in your database an existing Reimbursement with document_type = 4.
Or build one using this `document_id='6841408'` (Or any other `document_id` of a Reimbursement with electronic receipt - https://jarbas.serenata.ai/dashboard/chamber_of_deputies/reimbursement/?document_type=4) to be sure that it is a valid document_id with the right type and run:
```bash
docker-compose …
```

Fix receipt url of reimbursements with electronic receipts

---

rosie/rosie/chamber_of_deputies/classifiers/meal_price_outlier_classifier.py
rosie/rosie/chamber_of_deputies/tests/fixtures/meal_price_outlier_classifier.csv

To address the bug discussed in #506 
Before using a string method within the classifier, I used Pandas `fillna`  to replace `np.nan` (a _float_) by an empty string.
I added an empty value as a feature, so `python rosie.py test chamber_of_deputies` is an option. But fully running Rosie with `python rosie.py run chamber_of_deputies` is also advised.
@sergiomario @luizfzs

Ensure company name is string in meal outlier classifier

---

rosie/rosie/chamber_of_deputies/adapter.py

The issue happened when running Rosie on 2020-01-01. By the way the `adapter.py` works, it tries to fetch reimbursement files up to the year in which the application is running e.g. 2020. Since there is no such URL (at the time of this commit), the whole process fails due to an `HTTPError 404`. 
By adding this handling, the reimbursements that cannot be found are skipped from the download process and the application runs without any issues.
The goal of this PR is to add error handling to `adapter.py` when attempting to obtain a reimbursement that doesn't exist on the Chamber of Deputies website. If someone runs Rosie today (at least by the time this PR has been created), they are going to get an error when trying to obtain the reimbursement …

Add HTTPError handling when ReimbursementsURL doesn't exist

---

contrib/update/update.yml

From times to times Jarbas is missing the search vector, i.e., when users try to search through the search bar, no results are returned.
I know there is a scheduled Celery task to rebuild the search vector from time to time (depending on environment configuration). I'm not sure if the production environment is using it or not. Either way, maybe having it as a fixed step in the update playbook might better address this issue.
It's possible to tweak the playbook and run it locally to see if it works. Or brace yourselves and run it in production. The trick is to use a textual search (for example, an existing congresspeople name or a CNPJ) and expect to see results!

Adds a task to rebuild the search vector

---

jarbas/layers/elm/Reimbursement/Company/View.elm
jarbas/layers/elm/Reimbursement/Map/View.elm
jarbas/layers/elm/Reimbursement/Receipt/View.elm
jarbas/layers/elm/Reimbursement/RelatedTable/View.elm
jarbas/layers/elm/Reimbursement/Tweet/View.elm
jarbas/layers/elm/Reimbursement/View.elm
jarbas/layers/templates/layers/home.html

Based on some observations in #421 and some of my own, this Pull Request intend to enhance the overall legibility of the document page in Jarbas.
- Organised the content using outlines cards
- Fixed weird spacings
- Hide "X results found" if not necessary (only 1 result)
- Used color only for interactive elements
- Improved typography hierarchy
Just go to a document page :) Got before/after screenshots here too
BEFORE
AFTER
Everyone :)
ps: This is my first pull request for an open source project ever :)

[Design] Improve Jarbas document page legibility

---

README.md
contrib/deploy.sh
jarbas/README.md

We made some changes to the repositories hosted on the Github platform. We changed the name of the default branch of our active repositories - which was previously “master” to “main”.
The change aims to review uses of language that can reinforce contexts of oppression. Although, in the scope of Github, the term master is not immediately associated with slavery, as in the case of the [Linux master/slaves analogy](https://www.theregister.com/2020/07/13/linux_adopts_inclusive_language/), its symbolic load is already sufficient to adopt a more neutral form.
@cuducos

New branch default: main
